### ISSUE TITLE
Authentication fails one time after successful 2-FA

### ISSUE THREAD

**Issue by msteiger** [Bisnode/kubectl-tbac#31]
When I use a tbac command with an old token, I am forwarded to the 2-FA workflow and when I complete it successfully, the command still fails with
```
error: You must be logged in to the server (Unauthorized)
```
When I run the same command again, it works successfully, skipping the 2-FA workflow since the token is valid. Happens in versoin 1.0.2, could be related to the Windows setup, since it does not seem to happen on MacOS.

**Comment by anderseknert** [comment]
This bug in kubectl will be fixed in [kubernetes 1.19](https://github.com/kubernetes/kubernetes/pull/91745) ;)
What version of kubectl-login are you using on that machine though? We have a workaround for this in [kubectl-login since version 1.1.0](https://github.com/Bisnode/kubectl-login/blob/master/CHANGELOG.md) so you'll likely see it fixed by upgrading.
